version: '3'

services:
  app:
    image: 

    environment:

  redis:
    image: "redis"
  web:
    # COMPLETE HERE
    build: .
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: 'redis'
    depends_on:
      - redis
    volumes: 
      - ./redis-vol:/data