version: '3'

services:
  redis:
    image: "redis"
    restart: always
  web:
    build: .
    ports:
      - "5000:8080"
    depends_on:
      - redis
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    
    volumes: 
      - ./redis-vol:/data